# this is a plugin that can later be used, by itself, it does not apply the rate-limiting
# usage: k annotate -n kong service echo konghq.com/plugins=rate-limit-5-min
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-5-min
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 5
  policy: local
